// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IGroth16Verifier
 * @notice Interface for the auto-generated Groth16 verifier contract (snarkjs).
 *
 * The verifier is generated by:
 *   snarkjs zkey export solidityverifier bls_commitment.zkey Groth16Verifier.sol
 *
 * Public signals layout (7 signals):
 *   [0] commitment_hi   — upper 128 bits of SHA256(pk || sig || msg)
 *   [1] commitment_lo   — lower 128 bits of SHA256(pk || sig || msg)
 *   [2] pk_hash_hi      — upper 128 bits of SHA256(pk)
 *   [3] pk_hash_lo      — lower 128 bits of SHA256(pk)
 *   [4] payload_hash_hi — upper 128 bits of SHA256(requestId || y || pi || seed || mod)
 *   [5] payload_hash_lo — lower 128 bits of SHA256(requestId || y || pi || seed || mod)
 *   [6] request_id      — the request ID this proof binds to
 */
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata _pA,
        uint[2][2] calldata _pB,
        uint[2] calldata _pC,
        uint[7] calldata _pubSignals
    ) external view returns (bool);
}
