#!/usr/bin/env bash

set -euo pipefail

echo "============================================"
echo "  Halo2/KZG Setup (No Trusted Setup Required)"
echo "============================================"
echo ""
echo "Unlike Groth16/Circom, Halo2 with KZG uses a UNIVERSAL"
echo "Structured Reference String (SRS) that:"
echo "  - Is NOT circuit-specific"
echo "  - Does NOT require a per-circuit trusted ceremony"
echo "  - Can be generated deterministically"
echo "  - Same SRS works for any circuit up to size 2^k"
echo ""
echo "The Halo2 prover and verifier are implemented in Rust:"
echo "  off-chain/halo2_prover/"
echo ""
echo "To generate Halo2 proofs:"
echo "  cd off-chain"
echo "  cargo test -p halo2_prover -- --nocapture"
echo ""
echo "To run the full pipeline with Halo2:"
echo "  cd off-chain"
echo "  cargo test -p crypto_engine -- --nocapture"
echo ""
echo "The Solidity verifier is at:"
echo "  contracts/src/Halo2Verifier.sol"
echo ""
echo "============================================"
echo "  No setup ceremony needed! ✅"
echo "============================================"
